rbac:
  enabled: true
#--------------------------------------------------------
kibana:
  name: kibana
  replicaCount: 1
  image:
    repository: docker.elastic.co/kibana/kibana
    tag: 7.2.0
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 5601
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - kibana.dev
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
#--------------------------------------------------------
elasticsearch:
  name: elasticsearch
  storageClassname: storage-volume
  replicaCount: 3
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    tag: 7.2.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9200
    interport: 9300
  resources:
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
#--------------------------------------------------------
fluentdElasticsearch:
  name: fluentd
  namespace: logging
  image:
    repository:  fluent/fluentd-kubernetes-daemonset
    tag: v1.4.2-debian-elasticsearch-1.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  nodeSelector: {}
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  affinity: {}
  dockerContainersPath: /var/lib/docker/containers
  varlog: /var/log

