kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    app: {{ .Values.elasticsearch.name }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  clusterIP: None
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      name: rest
    - port: {{ .Values.elasticsearch.service.interport }}
      name: inter-node