apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  labels:
    app: {{ .Values.kibana.name }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - port: {{ .Values.kibana.service.port }}
  selector:
    app: kibana